mybatis:
  type-aliases-package: com.yejunyu.seckill.domain
  type-handlers-package: com.yejunyu.seckill.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/testdb
      password: 123456
      username: root

redis:
  host: localhost
  port: 6379
  timeout: 3
  poolMaxTotal: 8
  poolMaxIdle: 8
  poolMaxWait: 3
